language: scala
jdk:
  - oraclejdk8

scala:
  - 2.12.3

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.sbt/0.13
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
